import = [
    "~/.config/alacritty/themes/themes/gruvbox.toml"
]

[shell]
program = "/usr/bin/zsh"

[font]
size = 11

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Medium Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[scrolling]
history = 1000
multiplier = 3

[window]
dynamic_padding = true
opacity = 1

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 4
y = 4
